### ISSUE TITLE
Volume up multiple Degrees 

### ISSUE THREAD

**Issue by nis1g** [nitaybz/homebridge-samsung-remote#1]
Works on UN75MU800D or UN75MU8000 , KEY_HDMI1 doesn't work, but Change HDMI Command Works ,

Is there a Way to raise volume 5 Steps at a time , like 5 Numbers at a time ? the Key_VOLUP works well and  raises the Volume only ONE number up ?

**Comment by nitaybz** [comment]
KEY_HDMI1 is not working for me either.... but KEY_HDMI is working to change HDMI, I created this switch and a scene that called "Change HDMI" so I can tell siri to change HDMI now.

I'll working on a fix for the repeat option...

**Comment by nitaybz** [comment]
try to install the new version from git:
`sudo npm install -g https://github.com/nitaybz/homebridge-samsung-remote`
more details on the config you can find here:
[https://github.com/nitaybz/homebridge-samsung-remote/blob/master/README.md](https://github.com/nitaybz/homebridge-samsung-remote/blob/master/README.md)

if that works for you I'll update to npm

**Comment by nis1g** [comment]
thank you

**Comment by nis1g** [comment]
Hello,
Unfortunately i Couldn't install for some reason , the error msg is "only absolute urls are supported".

Also is there a way to get an Auto-Power-Status update , power status only updates manually when opening HomeKit App, and will not update automatically.

i am using siri/Homepod to tun on/off the tv and it doesn't always work and when it does , the on/off commands are inverted ( on for off ) unless you refresh status by opening HomeKit app first.

**Comment by nitaybz** [comment]
hey...
I will update the main version so you can install it properly...

regarding the auto-power... I can make it poll for status but to be honest I don't see the point of it, unless you set an automation based on the TV power...

regarding your last issue I found an error in the code... will be solved soon...

**Comment by nitaybz** [comment]
the plugin is updated now... please install with:
`sudo npm install -g homebridge-samsung-remote`

**Comment by nis1g** [comment]
Hello,

Thank you for the update , i was able to update successfully , the repeat works great !

i will waiting for the Power-Status update

**Comment by nitaybz** [comment]
why would you want the power status to be updated?

**Comment by nis1g** [comment]
Power On Command doesn't work properly when using Scenes or Voice Command to turn on TV , after i have turned it off manually or by remote .

Seems like Power-Status in HomeKit is the one last updated manually by opening HomeKit app, and does not update in real time to match actual power status of tv .

 Polling Status when Command is issued , or timed Auto polling Power Status maybe a fix to this ?

**Comment by nitaybz** [comment]
Regardless of the polling status... I think I know what the problem is and that I can fix it.
does the problem occur the other way around? can't turn off when you turned on manually?

**Comment by nis1g** [comment]
i just checked again! it is Working Now ! Maybe your updated Fixed it ?
After the update it says Now [XXXXXXXX] Setting TV to OFF /ON ,  and [ XXXXXXX] TV is Already ON 
i will try it over the next couple of days and let you know.



![img_1117](https://user-images.githubusercontent.com/35738480/36949607-7f5f640a-1f9f-11e8-939e-918598f56292.JPG)
