### ISSUE TITLE
Wake On Lan UE50KU6000

### ISSUE THREAD

**Issue by laloutr3** [nitaybz/homebridge-samsung-remote#11]
Hello,

First, thank you for this plugin :) 
I just have trouble with Power On : it does not work, even though I have correctly set IP and MAC address, and TV is connected with ethernet cable... Everything else works fine, including power off. And, weird, if a I turn OFF then quickly turn ON, it does turn on the TV... maybe it is not completly turned off at this particular moment and API is still available.

I run Homebridge with a docker container on a Synology. 

Do you have any idea why it is not working ? Which port is used ?

Thanks !

**Comment by nitaybz** [comment]
no idea why.... default port is 9...

**Comment by laloutr3** [comment]
Thanks for your response :) 

The port is an useful info for me. Regarding my researches on Google, it seems that the problem is located with Docker, which does not process the request, I'll investigate that.
