### ISSUE TITLE
Does this work with the HU6900?

### ISSUE THREAD

**Issue by eneski** [nitaybz/homebridge-samsung-remote#12]
I already tried to use this, but nothing works, not even power off. I don't know how to find out the firmware it has on it so it would be great if you could tell me.

**Comment by alessandrocroci** [comment]
I have the same model and I don't understand wich plugin I have to use....
can someone help me? this tv have the tizen software or not?

if I connect via browser at this address http://192.168.1.200:8001/api/v2/ the tv give back this information:
{
  "id": "07270e01-0078-1000-8cd0-5056bfdf3d83",
  "name": "[TV]Samsung UHD50",
  "version": "2.0.24",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "07270e01-0078-1000-8cd0-5056bfdf3d83",
    "model": "14_NT14U_2D_BT",
    "modelName": "UE50HU6900",
    "description": "Samsung TV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.1.200",
    "firmwareVersion": "Unknown",
    "name": "[TV]Samsung UHD50",
    "id": "07270e01-0078-1000-8cd0-5056bfdf3d83",
    "udn": "07270e01-0078-1000-8cd0-5056bfdf3d83",
    "resolution": "1920x1080",
    "countryCode": "IT",
    "msfVersion": "2.0.24",
    "smartHubAgreement": "true",
    "developerMode": "0",
    "developerIP": "0.0.0.0"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.1.200:8001/api/v2/"
}

**Comment by kkapitan** [comment]
Hi, guys i've made a plugin that should work with H and J series. It is still in progress (turning on does not work right now) but all of the other commands should be possible. You can find it [here](https://github.com/kkapitan/homebridge-homesung) just follow the README to set things up. Feel free to test it and leave your comments :) Hope it will solve our issues with that models.

**Comment by eneski** [comment]
@kkapitan hey, I wanted to setup your plugin, but don't exactly know how. Do I have to pair with the TV before configuring the json file or what? please tell me what comes after installing the plugin

**Comment by kkapitan** [comment]
Hey @eneski - there should be a guide in README.md. Yes, you need to pair with the TV first as described [here](https://github.com/kkapitan/homebridge-homesung#pairing). Then use the info like `deviceId`, `sessionId` and `aesKey` to fill the homebridge's `config.json` inside your `~/.homebridge` directory according to the sample provided [here](https://github.com/kkapitan/homebridge-homesung#configuration).

**Comment by eneski** [comment]
@kkapitan OK, so I installed the plugin and ran homesung-pair with the ip. But all I get is some error? http://prntscr.com/ksv58t

**Comment by kkapitan** [comment]
From the provided screenshot it looks like you are using the old version of `Node.js`. Can you show me what `node -v` prints for you? Ideally it should be version above `6.4.0`.

**Comment by eneski** [comment]
@kkapitan http://prntscr.com/ksvb0g I just updated everything, don't think that's the issue

**Comment by kkapitan** [comment]
The issue with unexpected token `...` suggests that the node environment does not support JS ES6 spread/rest syntax which was a thing in node pre `6.4.0` I think. Maybe the default env this script is executed with is older. Try going to the location of the `homebridge-homesung` node_module and go with `node bin/pair <your_ip_address>`.

**Comment by eneski** [comment]
@kkapitan hey, I don't know much about all of this. How do I go to the location of the plugin?

**Comment by kkapitan** [comment]
Try `/usr/local/lib/node_modules/homebridge-homesung`

**Comment by eneski** [comment]
@kkapitan still the same thing http://prntscr.com/ksvwt2

**Comment by kkapitan** [comment]
I've just checked and it seems that spread operator is supported from the node `8.6.0` and with `8.2.1` it should work with flag `--harmony`. Can you check if running the `node --harmony bin/pair <your_ip_address>` inside the plugin directory at least changes the error?

The newest node version is ~10 if i remember correctly, so it seems there are still updates for you to be installed.

**Comment by eneski** [comment]
@kkapitan now I was able to pair them. But now my homebridge does not want to start. I get this error again http://prntscr.com/kswb35 . By updating I mean sudo apt-get update and upgrade. Is there something else I have to do

**Comment by kkapitan** [comment]
Maybe try `apt-get update && apt-get install nodejs`. I'm not experienced with RPI setup unfortunately.  If it didn't work try running homebridge like that `node --harmony /usr/local/lib/node_modules/homebridge/bin/homebridge` but this should be only a temporary solution. The primary one is to somehow upgrade the nodejs

**Comment by eneski** [comment]
@kkapitan it tells me that I already have the newest version installed

**Comment by kkapitan** [comment]
Does running homebridge with `--harmony` help? As for version I've found [this thread](https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-Install-Node.js-via-Package-Manager-*(Recommended)*). I think this fetches node v10 from the repo directly, maybe your apt-get repo registry does not have it.

**Comment by eneski** [comment]
I tried updating it and it tells me that version 10 is installed. but when I check with node -v it still tells me it's 8.2.1. http://prntscr.com/kswsb0 sorry it's in german

**Comment by kkapitan** [comment]
The other option would be to install node via `nvm`. You can check how to do it [here](https://www.losant.com/blog/how-to-install-nodejs-on-raspberry-pi). For version use `8.6.0` or any newer. 

I would also recommend doing `apt-get remove --purge nodejs` before, to clean the old node.js installation.

**Comment by eneski** [comment]
Now I was able to update it and it works again. But now homebridge does not start automatically when powering on the Pi.

**Comment by nitaybz** [comment]
There is a a better plugin these days called [Homebridge-Samsung-Tizen](https://github.com/tavicu/homebridge-samsung-tizen/), it is updated with the recent updates to security that should support the new firmware and fix the issues you experience.

The author @tavicu is also working on an upgrade to the plugin to support the new HomeKit TV accessory. you can read about it and install the beta version [HERE](https://github.com/tavicu/homebridge-samsung-tizen/pull/67)
