### ISSUE TITLE
Samsung Remote Client:undefined with Q7FN (2018)

### ISSUE THREAD

**Issue by flobernd** [nitaybz/homebridge-samsung-remote#13]
Hi there,

I just tried your plugin with my Q7FN. Wake on LAN (ON) works well, but powering OFF and muting just prints "Samsung Remote Client:undefined" on the terminal.

Here is the output of my API URL:
```json
{
  "device": {
    "FrameTVSupport": "false",
    "GamePadSupport": "true",
    "ImeSyncedSupport": "true",
    "OS": "Tizen",
    "TokenAuthSupport": "true",
    "VoiceSupport": "true",
    "countryCode": "DE",
    "description": "Samsung DTV RCR",
    "developerIP": "0.0.0.0",
    "developerMode": "0",
    "duid": "uuid:7f7a5e4b-1d6b-49e7-9aa5-5a347a3db72f",
    "firmwareVersion": "Unknown",
    "id": "uuid:7f7a5e4b-1d6b-49e7-9aa5-5a347a3db72f",
    "ip": "192.168.178.129",
    "model": "18_KANTM2_QTV",
    "modelName": "QE55Q7FNA",
    "name": "[TV] Samsung Q7 Series (55)",
    "networkType": "wired",
    "resolution": "3840x2160",
    "smartHubAgreement": "true",
    "type": "Samsung SmartTV",
    "udn": "uuid:7f7a5e4b-1d6b-49e7-9aa5-5a347a3db72f",
    "wifiMac": "64:1c:b0:a5:05:7d"
  },
  "id": "uuid:7f7a5e4b-1d6b-49e7-9aa5-5a347a3db72f",
  "isSupport": "{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n",
  "name": "[TV] Samsung Q7 Series (55)",
  "remote": "1.0",
  "type": "Samsung SmartTV",
  "uri": "http://192.168.178.129:8001/api/v2/",
  "version": "2.0.25"
}
```

Best regards

**Comment by KelixAU** [comment]
I have the same issue now after a firmware update for a 2017 QLED. Is there anything we can do to get back the functionality @nitaybz? How can we help?

**Comment by JonoHaysom** [comment]
Is there anything we can do to get back the functionality?

**Comment by nitaybz** [comment]
I don’t have the time to research on the new update changes... if you find any reference to this online just post it here and I’ll review :)

**Comment by logictester** [comment]
is this something that might work: https://www.npmjs.com/package/samsung-remote

**Comment by KelixAU** [comment]
@nitaybz the above looks like it could do the trick if you could implement

**Comment by nitaybz** [comment]
There is a a better plugin these days called [Homebridge-Samsung-Tizen](https://github.com/tavicu/homebridge-samsung-tizen/), it is updated with the recent updates to security that should support the new firmware and fix the issues you experience.

The author @tavicu is also working on an upgrade to the plugin to support the new HomeKit TV accessory. you can read about it and install the beta version [HERE](https://github.com/tavicu/homebridge-samsung-tizen/pull/67)
