### ISSUE TITLE
Suport for Remotes (New homekit accessories for ios12)

### ISSUE THREAD

**Issue by erokoder** [nitaybz/homebridge-samsung-remote#14]
@nitaybz 
Do you have a plan to support new accessories Remotes for third party device (Samsung) over homebridge samsung remote?

**Comment by KelixAU** [comment]
This would be a great addition! @nitaybz

**Comment by nitaybz** [comment]
I haven’t seen any homekit-homebridge reference regarding the new remote characteristic... sorry, we’ll have to wait...

**Comment by greensouth** [comment]
What about the new TV accessory?? It looks promising… at least for those who Samsung left without Homekit (2016 Tizen TVs)

[https://twitter.com/khaost/status/1088521851750379520?s=21](url)

**Comment by erokoder** [comment]
bump ios12.2 is available

**Comment by nitaybz** [comment]
There is a a better plugin these days called [Homebridge-Samsung-Tizen](https://github.com/tavicu/homebridge-samsung-tizen/), it is updated with the recent updates to security that should support the new firmware and fix the issues you experience.

The author @tavicu is also working on an upgrade to the plugin to support the new HomeKit TV accessory. you can read about it and install the beta version [HERE](https://github.com/tavicu/homebridge-samsung-tizen/pull/67)
