### ISSUE TITLE
Multiple commands are not working...

### ISSUE THREAD

**Issue by skbeez** [nitaybz/homebridge-samsung-remote#15]
I have a situation where only single commands work, if I send an array of commands, it does not work. Here's an excerpt from my config file:

```
"accessories": [
        {
            "accessory": "SamsungTV",
            "name": "Living Room TV",
            "ip": "192.168.1.88",
            "mac": "xx:xx:xx:xx:xx:xx",
            "type": "power"
        },
        {
            "accessory": "SamsungTV",
            "name": "Mute TV",
            "ip": "192.168.1.88",
            "mac": "xx:xx:xx:xx:xx:xx",
            "type": "mute"
        },
        {
            "accessory": "SamsungTV",
            "name": "Volume Up",
            "ip": "192.168.1.88",
            "mac": "xx:xx:xx:xx:xx:xx",
            "type": "custom",
            "command": "KEY_VOLUP",
            "repeat": 5,
            "delay": 500
        },
        {
            "accessory": "SamsungTV",
            "name": "Volume Down",
            "ip": "192.168.1.88",
            "mac": "xx:xx:xx:xx:xx:xx",
            "type": "custom",
            "command": "KEY_VOLDOWN",
            "repeat": 5,
            "delay": 500
        },
        {
            "accessory": "SamsungTV",
            "name": "Netflix",
            "ip": "192.168.1.88",
            "mac": "xx:xx:xx:xx:xx:xx",
            "type": "custom",
            "command": [
                "KEY_HOME",
                "KEY_RIGHT"
            ],
            "delay": 500
        }
    ],
```

Everything works except for the Netflix command. Here's the output from Homebridge:

```
Oct 19 21:09:46 smarthub homebridge[6927]: [2018-10-19 21:09:46] [Netflix] Sending KEY_HOME,KEY_RIGHT command to TV
Oct 19 21:09:46 smarthub homebridge[6927]: [2018-10-19 21:09:46] [Netflix] KEY_HOME,KEY_RIGHT command sent
```
But the TV does nothing... If I change the command to just be a single command "KEY_HOME", it will bring up the menu as expected. Any idea what's going on?

**Comment by KelixAU** [comment]
the new firmware seems to have changed a bit. many of us just have power on.. no other function will work. :( we need to get new details on the encrypted API's

**Comment by skbeez** [comment]
Oh well in that case I should mention that when the volume command is sent it actually increases the volume of my Yamaha receiver and not the TV. That doesn't bother be too much as that's the device that handles all the audio anyway. As it appears HDMI-CEC seems to be working still.

**Comment by nitaybz** [comment]
@skbeez try to increase the delay

**Comment by tompacyk** [comment]
Having the same issue (even after adjusting delay). It almost looks like the multi-command send is lumping everything together as a single send instead of issuing the commands in sequence. I can't totally tell if that's true, but it might be nice to have the debug log show each individual command being sent. Also noticed that after I try to turn on a multi-command my other custom switches stop working. 

This is me trying to hack around the inability to select a specific HDMI input (what a _terrible_ design choice on the KS8000 TV!)
```
        {
            "accessory": "SamsungTV",
            "name": "Comcast",
            "ip": "172.16.0.32",
            "mac": "12:34:56:78:90:12",
            "type": "custom",
            "command": ["KEY_SOURCE", "KEY_LEFT", "KEY_LEFT", "KEY_LEFT", "KEY_LEFT", "KEY_LEFT", "KEY_RIGHT", "KEY_RIGHT", "KEY_RIGHT", "KEY_ENTER"],
            "delay": 1000
        },
```

**Comment by nitaybz** [comment]
There is a a better plugin these days called [Homebridge-Samsung-Tizen](https://github.com/tavicu/homebridge-samsung-tizen/), it is updated with the recent updates to security that should support the new firmware and fix the issues you experience.

The author @tavicu is also working on an upgrade to the plugin to support the new HomeKit TV accessory. you can read about it and install the beta version [HERE](https://github.com/tavicu/homebridge-samsung-tizen/pull/67)
