### ISSUE TITLE
New TV firmware

### ISSUE THREAD

**Issue by Maxwell70** [nitaybz/homebridge-samsung-remote#16]
In October 2018, the TV (MU 6100) was updated to the new firmware (1250.5). After that, I can't control it. Is there anything we can do? Can downgrade the firmware version in the TV or do something in the service menu of the TV?

**Comment by nitaybz** [comment]
There is a a better plugin these days called [Homebridge-Samsung-Tizen](https://github.com/tavicu/homebridge-samsung-tizen/), it is updated with the recent updates to security that should support the new firmware and fix the issues you experience.

The author @tavicu is also working on an upgrade to the plugin to support the new HomeKit TV accessory. you can read about it and install the beta version [HERE](https://github.com/tavicu/homebridge-samsung-tizen/pull/67)
