### ISSUE TITLE
None of the commands are working anymore

### ISSUE THREAD

**Issue by alikhodrali** [nitaybz/homebridge-samsung-remote#17]
None of the commands are working anymore due to a new update. Can we expect a fix soon?

**Comment by jagpreetbatth** [comment]
+1 to this Issue, none of the commands work. Just SHOWS if TV is on or off in Home app but can not control the TV at ALL?

**Comment by denzel1994** [comment]
+1
Same issue here. None of the commands work anymore. UE55MU6179 with firmware 1260.6

**Comment by nis1g** [comment]
Stopped Working , says **Samsung Remote Client:undefined**

**Comment by nitaybz** [comment]
There is a a better plugin these days called [Homebridge-Samsung-Tizen](https://github.com/tavicu/homebridge-samsung-tizen/), it is updated with the recent updates to security that should support the new firmware and fix the issues you experience.

The author @tavicu is also working on an upgrade to the plugin to support the new HomeKit TV accessory. you can read about it and install the beta version [HERE](https://github.com/tavicu/homebridge-samsung-tizen/pull/67)
