### ISSUE TITLE
Samsung QA65Q8C

### ISSUE THREAD

**Issue by PaiSolutions** [nitaybz/homebridge-samsung-remote#3]
**Working:** Power, Mute. **Not working:** vol up, vol down, hdmi. Will update when i play around more.

**Comment by nitaybz** [comment]
There is a a better plugin these days called [Homebridge-Samsung-Tizen](https://github.com/tavicu/homebridge-samsung-tizen/), it is updated with the recent updates to security that should support the new firmware and fix the issues you experience.

The author @tavicu is also working on an upgrade to the plugin to support the new HomeKit TV accessory. you can read about it and install the beta version [HERE](https://github.com/tavicu/homebridge-samsung-tizen/pull/67)
