### ISSUE TITLE
Volume doesn't work with Siri

### ISSUE THREAD

**Issue by nmajin** [nitaybz/homebridge-samsung-remote#4]
Can you provide an example of how you got it working? The sample config is not recognizing the command. I wonder if it is conflicting with Siri's default media controls. I am using the latest version from npm.org.

**Comment by nmajin** [comment]
Works like 3% of the time naming it like this:

[2018-3-4 18:09:18] [TV Volume Up] KEY_VOLUP command sent
[2018-3-4 18:09:41] [TV Volume Down] KEY_VOLDOWN command sent

**Comment by nitaybz** [comment]
not every command will work on your TV.
which model do you have?

**Comment by nitaybz** [comment]
does your other commands work?

**Comment by nmajin** [comment]
"type": "Samsung SmartTV"
"model": "16_JAZZL_UHD_BASIC"
"modelName": "UN55KU6290"

**Comment by nmajin** [comment]
Yea, volume is the only one that is working less than 10% of the time

**Comment by nmajin** [comment]
It's something to do with Siri, commands work fine.

**Comment by nitaybz** [comment]
what happen when you press the accessory in home app? is it always working?

**Comment by nmajin** [comment]
Yea, that works, so it's an issue with Siri. She must be overriding speech like "volume" and not understanding it for a home bridge accessory.

**Comment by nitaybz** [comment]
exactly... it's a know issue with homekit. you can't call your accessories in names which are already related to apple music / player

**Comment by nmajin** [comment]
Seems like the sweet spot is to name it, "Increase TV Volume" and "Decrease TV Volume". Take note of this :-)

**Comment by nis1g** [comment]
{
      "accessory": "SamsungTV",
      "name": " Volume Up”,
      "accessory": "SamsungTV”,
      "ip": "192.168.1.32",
      "mac": "84:c0:ef:a7:0f:46",
      "type": "custom",
      "command": "KEY_VOLUP"
      "repeat": 3,
      "delay": 500
    }

 {
      "accessory": "SamsungTV",
      "name": " Volume Down”,
      "accessory": "SamsungTV”,
      "ip": "192.168.1.32",
      "mac": "84:c0:ef:a7:0f:46",
      "type": "custom",
      "command": "KEY_VOLDOWN"
    }

Mine works every time and all the times, there is a slight response delay when command is sent but not a very noticeable one, In my HomeKit app i named it "Volume Up TV ", Joined it to Living-Room Room, Siri Responds to " Hey Siri ... Volume Up TV"  Only.... and will not respond if you say living room or anything else. i also had to rename the Power in HomeKit to " Living Room TV ", Siri will respond to " Turn On/Off Living Room TV".


![image 2](https://user-images.githubusercontent.com/35738480/36949037-f67430c8-1f97-11e8-893e-f8f629e81197.png)

![image](https://user-images.githubusercontent.com/35738480/36949015-b5d809b8-1f97-11e8-923f-a07d562b868e.png)





Please note that my TV is on a wired gigabit network with a Static IP ,,, NOT wireless  .... the type of connection to the TV might be the issue ? i know the Power-On/ wake-up on Lan works on wired networks only with the correct Wired-MAC-Address in the Config file.

**Comment by nmajin** [comment]
Yea that is odd, I am hardwired with a static IP. I named my "power" accessory "TV" which works fine. It is working 100% of the time naming it "Increase/Decrease TV Volume" so should be good to go with that.

Thanks

**Comment by langovoi** [comment]
You can use my plugin for control volume with slider in HomeKit and with Siri: https://github.com/langovoi/homebridge-upnp#readme
