### ISSUE TITLE
UE48J6272

### ISSUE THREAD

**Issue by pax0707** [nitaybz/homebridge-samsung-remote#5]
Should this work with my TV, it's 2015 but it's Tizen?

MN : UE48J6200 
PD : --/--/---- 
SN : 
FW : T-HKMFDEUC-1520.2 
FC : SWU-OU_T-HKMFDEUC-1520.2_20171109 
MI : T-HKMFDEUC 
LS : EU 
DI : XTCISIBYQK3NM 
MA : E47DBDC34508 
VS : 1520.2.20171109

**Comment by nitaybz** [comment]
if it's Tizen, I guess it should work... why don't you try and tell us? :)

**Comment by pax0707** [comment]
Can't get it to work.

Is it an issue if TV is connected over WiFi?

**Comment by nis1g** [comment]
Wifi is ok if the TV has a static ip address , Power On will not work on Wifi

**Comment by pax0707** [comment]
Can't make it work.

Shouldn't there be a need to pair it with PIN or something like that?

**Comment by nitaybz** [comment]
I’m not sure... in my tv I think I had a notification on the tv screen asking me to approve the app

**Comment by OhHeyAlan** [comment]
@nis1g Power on over Wifi will work if the IP and the MAC are set.

**Comment by kkapitan** [comment]
Hi, guys i've made a plugin that should work with H and J series. It is still in progress (turning on does not work right now) but all of the other commands should be possible. You can find it [here](https://github.com/kkapitan/homebridge-homesung) just follow the README to set things up. Feel free to test it and leave your comments :) Hope it will solve our issues with that models.
