### ISSUE TITLE
Sleep command

### ISSUE THREAD

**Issue by tavicu** [nitaybz/homebridge-samsung-remote#6]
Hei. I need the a command for setting a sleep time.

My approach is to send a set of keys, example: KEY_SLEEP, KEY_ENTER, KEY_DOWN * time option, KEY_ENTER.
with a new command, "sleep" and an option "time" with 0 for off, 1 for 30 minutes, 2 for 60 minutes, etc. The options from the dropdown.

I can do this change. The question is if you are open to this. I can send a pull request if you want it.
Of maybe you have a better idea for this.

**Comment by thehauntedmattress** [comment]
Are you saying that you are trying to and/or able to send a series of keys using a single homekit button?

**Comment by tavicu** [comment]
Yes. Just like repeat function but with different keys!

I’ve seen your open issue. I will try to make some changes today and get back to you!
