### ISSUE TITLE
UE60JU6000KXXU

### ISSUE THREAD

**Issue by lowrisk75** [nitaybz/homebridge-samsung-remote#9]
There is no error detected on Homebridge but the TV seems not responsible 

 {
            "accessory": "SamsungTV",
            "name": "Living Room TV",
            "ip": "10.0.x.x",
            "mac": "xx:bb:xx:xx:xx:xx",
            "type": "power"
        },

I have a older samsung tv in the kitchen, didn't try with this one yet.

**Comment by pax0707** [comment]
J series is Tizen but counldn't make this work with it.

**Comment by nitaybz** [comment]
Power ON command only works with Ethernet cable connected... did you try that? How about turning off the TV when it’s ON?

**Comment by F9R** [comment]
On my UE55JU7090 german model from 2015 I have same problem, homebridge logs commands invoking successfully but it's not working.
Tested power and channel up.

**Comment by kkapitan** [comment]
Hi, guys i've made a plugin that should work with H and J series. It is still in progress (turning on does not work right now) but all of the other commands should be possible. You can find it [here](https://github.com/kkapitan/homebridge-homesung) just follow the README to set things up. Feel free to test it and leave your comments :) Hope it will solve our issues with that models.

**Comment by nitaybz** [comment]
There is a a better plugin these days called [Homebridge-Samsung-Tizen](https://github.com/tavicu/homebridge-samsung-tizen/), it is updated with the recent updates to security that should support the new firmware and fix the issues you experience.

The author @tavicu is also working on an upgrade to the plugin to support the new HomeKit TV accessory. you can read about it and install the beta version [HERE](https://github.com/tavicu/homebridge-samsung-tizen/pull/67)

**Comment by pax0707** [comment]
Does that work on J series?
